# Generated by Django 6.1 on 2026-08-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('localisation', models.CharField(max_length=200)),
                ('capacite_installee_mw', models.DecimalField(decimal_places=2, help_text='Capacité installée en mégawatts (MW)', max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProductionJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energie_produite_mwh', models.DecimalField(decimal_places=2, help_text='Énergie produite en MWh', max_digits=10)),
                ('barrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='energie.barrage')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('barrage', 'date'), name='unique_production_par_jour')],
            },
        ),
        migrations.CreateModel(
            name='ReleveNiveauEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('niveau_m', models.DecimalField(decimal_places=2, help_text="Niveau d'eau en mètres", max_digits=6)),
                ('barrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_niveau', to='energie.barrage')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('barrage', 'date'), name='unique_releve_par_jour')],
            },
        ),
    ]
